---
abstract: 'bindings for librdkafka'
author:
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.94'
configure_requires:
  Alien::Librdkafka: v0.9.1
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Kafka-Librd
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Librdkafka: v0.9.1
  Exporter::Lite: '0'
resources:
  bugtracker: https://github.com/trinitum/perl-Kafka-Librd/issues
  homepage: https://github.com/trinitum/perl-Kafka-Librd
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trinitum/perl-Kafka-Librd
version: '0.01'
x_contributors:
  - 'Pavel Shaydo <zwon@cpan.org>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
